server:
  port: 8080

spring:
  application.name: explorer-service
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
      READ_ENUMS_USING_TO_STRING: true
  sql:
    init:
      mode: ALWAYS
  jdbc:

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
#    hibernate:
#      ddl-auto: create

#logging:
#  level:
#    org:
#      springframework:
#        jdbc:
#          core:
#            JdbcTemplate: debug


